"""Public package metadata and collection-mapping contracts."""

ENGINE_VERSION = "0.11.0"
ARTIFACT_SCHEMA_VERSION = "1.10"
__version__ = ENGINE_VERSION

from .models import (  # noqa: E402 - version constants must exist before api imports this module
    ArtifactManifest,
    ClusterSourceContribution,
    ClusterProposal,
    ClusterSynthesis,
    CoverageRecord,
    CoverageRegister,
    DebateFamily,
    EvidenceAnchor,
    EvidenceBaseGroup,
    EvidenceThread,
    EvidenceFinding,
    EvidenceProfile,
    ExtractionPolicy,
    GapAnchor,
    GapRationale,
    GapStudyDesign,
    GapValueAssessment,
    IndependenceAssessment,
    LiteratureMapReport,
    LiteratureMapRequest,
    LiteratureMappingPolicy,
    LiteratureProposition,
    MapRequest,
    NavigationPolicy,
    NeighborhoodSummary,
    ProcessingPolicy,
    QuantitativeComparisonValidation,
    QuantitativeResult,
    ResolutionPath,
    RunReport,
    SourceLocator,
    StudyLineage,
    SynthesisAssertion,
    StatusReport,
    SupportEnvelope,
    SubjectTag,
    SubjectTagAssignment,
    TagConcept,
    TopicNeighborhood,
    TypedSourceRelation,
)
from .api import run_literature_map  # noqa: E402 - depends on the constants above
from .ports import (  # noqa: E402 - public protocols depend on the models above
    ClusterSynthesisReasoner,
    ExternalDiscoveryProvider,
    LiteratureReasoner,
)

__all__ = [
    "ARTIFACT_SCHEMA_VERSION",
    "ENGINE_VERSION",
    "__version__",
    "ArtifactManifest",
    "ClusterSourceContribution",
    "ClusterProposal",
    "ClusterSynthesis",
    "ClusterSynthesisReasoner",
    "CoverageRecord",
    "CoverageRegister",
    "DebateFamily",
    "EvidenceAnchor",
    "EvidenceBaseGroup",
    "EvidenceThread",
    "EvidenceFinding",
    "EvidenceProfile",
    "ExtractionPolicy",
    "ExternalDiscoveryProvider",
    "GapAnchor",
    "GapRationale",
    "GapStudyDesign",
    "GapValueAssessment",
    "IndependenceAssessment",
    "LiteratureMapReport",
    "LiteratureMapRequest",
    "LiteratureMappingPolicy",
    "LiteratureProposition",
    "LiteratureReasoner",
    "MapRequest",
    "NavigationPolicy",
    "NeighborhoodSummary",
    "ProcessingPolicy",
    "QuantitativeComparisonValidation",
    "QuantitativeResult",
    "ResolutionPath",
    "RunReport",
    "SourceLocator",
    "StudyLineage",
    "SynthesisAssertion",
    "StatusReport",
    "SupportEnvelope",
    "SubjectTag",
    "SubjectTagAssignment",
    "TagConcept",
    "TopicNeighborhood",
    "TypedSourceRelation",
    "run_literature_map",
]
